prometheus:
  configs:
    - name: default
      scrape_configs:
        - job_name: node
          static_configs:
          - targets: ['localhost:9100']
          scrape_interval: 10s

      remote_write:
        - url: ${PROM_URL}
          basic_auth:
            username: ${PROM_USERNAME}
            password: ${PROM_PASSWORD}
