name: collect

on:
  schedule:
    # scheduling is unreliable - every minute means every 15 to 30min actually - good enough
    - cron: "*/30 * * * *"
  workflow_dispatch:
    # allow manual triggering

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: prime-numbers
          key: primes

      - run: ls asd
        name: test
        continue-on-error: true

      - run: echo ${{ steps.test.conclusion }}
        if: success() || failure()

      - name: Generate Prime Numbers
        if: success() || steps.test.conclusion == 'failure'
        run: |
          A=$(cat prime-numbers/data.dat || echo 0)
          echo $A
          B=$(expr $A \+ 1)
          echo $B
          mkdir -p prime-numbers
          echo $B > prime-numbers/data.dat
      
      - name: Generate Prime Numbers
        if: success() || steps.test.conclusion == 'success'
        run: |
          mkdir -p prime-numbers
          echo 0 > prime-numbers/data.dat

      # - uses: actions/checkout@v3
      #   with:
      #     ref: data
      #     path: data
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.9
      # - run: pip install -r requirements.txt
      # - name: get coefficient
      #   run: |
      #     python main.py ${{ secrets.WALLET }} ${{ secrets.AVAX_URL }} --binary-log -o data/log.bin
      # - name: get population
      #   run: |
      #     python main_pop.py --binary-log -o data/pop.bin
      # # - name: get burn coefficient
      # #  run: |
      # #    python main_burn.py ${{ secrets.BURN_TOKEN }} ${{ secrets.BURN_SIGN }} ${{ secrets.BURN_WALLET }} ${{ secrets.BURN_AUTH }} --binary-log -o data/burn.bin
      # - name: push data
      #   run: |
      #     cd data
      #     git add log.bin pop.*.bin burn.bin
      #     git config user.email updater@devnull.localhost
      #     git config user.name Updater
      #     git commit log.bin pop.*.bin burn.bin -m update
      #     git push
