name: collect

on:
  schedule:
    # scheduling is unreliable - every minute means every 15 to 30min actually - good enough
    - cron: "*/30 * * * *"
  workflow_dispatch:
    # allow manual triggering

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: data
          path: data

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - run: pip install -r requirements.txt

      - name: get coefficient
        run: |
          python main.py ${{ secrets.WALLET }} ${{ secrets.AVAX_URL }} --binary-log -o data/log.bin

      - name: get population
        id: check_pop
        continue-on-error: true
        run: |
          python main_pop.py --binary-log -o data/pop.bin

      - name: handle API 403 fail
        if: steps.check_pop.outcome == 'failure'
        run: |
          A=$(cat data/fail.pop.dat || echo 0)
          B=$(expr $A \+ 1)
          echo $B fails in a row
          echo $B > data/fail.pop.dat

      - name: handle API 403 pass
        if: steps.check_pop.outcome == 'success'
        run: |
          echo 0 > data/fail.pop.dat

      # - name: get burn coefficient
      #  run: |
      #    python main_burn.py ${{ secrets.BURN_TOKEN }} ${{ secrets.BURN_SIGN }} ${{ secrets.BURN_WALLET }} ${{ secrets.BURN_AUTH }} --binary-log -o data/burn.bin

      - name: push data
        run: |
          cd data
          git add log.bin pop.*.bin burn.bin fail.*.dat
          git config user.email updater@devnull.localhost
          git config user.name Updater
          git commit log.bin pop.*.bin burn.bin fail.*.dat -m update
          git push
      
      - name: check failures
        run: |
          A=$(cat data/fail.pop.dat || echo 0)
          if [ "$A" -gt "9" ]; then
              echo "TOO MANY FAILURES"
              exit 1
          fi
