name: collect

on:
  workflow_dispatch:
    # allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: data
          path: data
      - uses: actions/checkout@v3
        with:
          ref: csv-hosting
          path: csv-hosting
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      
      - name: Reset csv-hosting
        run: |
          cd csv-hosting
          git reset --hard a6ccabfacd695d2293d8fda35bbdd53ed336d6c7

      - name: Convert all bin logs to csv
        run: |
          ./tocsv.py data/pop.working.bin --output csv-hosting/pop.working.csv
          ./tocsv.py data/pop.alive.bin --output csv-hosting/pop.alive.csv
          ./tocsv.py data/pop.dead.bin --output csv-hosting/pop.dev.csv
          ./tocsv.py data/log.bin --output csv-hosting/breed.coef.csv
          ./tocsv.py data/burn.bin -l --output csv-hosting/burn.coef.csv
          ./tocsv.py data/slimepool.bin -l --output csv-hosting/slimepool.csv
          ./tocsv.py data/rewardspool.bin -l --output csv-hosting/rewardpool.csv
      
      - name: Push csv-hosting
        run: |
          cd csv-hosting
          git add *.csv
          git config user.email updater@devnull.localhost
          git config user.name Updater
          git commit *.csv -m 'CSVs updated'
          git push --force
