name: collect

on:
  # UNRELIABLE
  # schedule:
  #  - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: data
          path: data
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: setup grafana agent
        run: |
          curl -LO https://github.com/grafana/agent/releases/download/v0.25.1/agent-linux-amd64.zip
          unzip agent-linux-amd64.zip
      - run: pip install -r requirements.txt
      - name: get coefficient
        run: |
          python main.py ${{ secrets.WALLET }} ${{ secrets.AVAX_URL }} -o data/log.txt --prom ./agent-linux-amd64 ${{ secrets.PROM_URL }} ${{ secrets.PROM_USERNAME }} ${{ secrets.PROM_PASSWORD }}
      - name: push data
        run: |
          cd data
          git config user.email updater@devnull.com
          git config user.name Updater
          git commit log.txt -m update
          git push
