name: collect

on:
  schedule:
    # scheduling is unreliable - every minute means every 15 to 30min actually - good enough
    - cron: "*/30 * * * *"
  workflow_dispatch:
    # allow manual triggering

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: data
          path: data

      - run: ls asd
        id: test
        continue-on-error: true

      - name: Generate Prime Numbers
        if: steps.test.outcome == 'failure'
        run: |
          A=$(cat data/fail.pop.dat || echo 0)
          echo $A
          B=$(expr $A \+ 1)
          echo $B
          echo $B > data/fail.pop.dat

      - name: Generate Prime Numbers
        if: steps.test.outcome == 'success'
        run: |
          echo 0 > data/fail.pop.dat

      # - uses: actions/checkout@v3
      #   with:
      #     ref: data
      #     path: data
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.9
      # - run: pip install -r requirements.txt
      # - name: get coefficient
      #   run: |
      #     python main.py ${{ secrets.WALLET }} ${{ secrets.AVAX_URL }} --binary-log -o data/log.bin
      # - name: get population
      #   run: |
      #     python main_pop.py --binary-log -o data/pop.bin
      # # - name: get burn coefficient
      # #  run: |
      # #    python main_burn.py ${{ secrets.BURN_TOKEN }} ${{ secrets.BURN_SIGN }} ${{ secrets.BURN_WALLET }} ${{ secrets.BURN_AUTH }} --binary-log -o data/burn.bin
      - name: push data
        run: |
          cd data
          git add log.bin pop.*.bin burn.bin fail.*.dat
          git config user.email updater@devnull.localhost
          git config user.name Updater
          git commit log.bin pop.*.bin burn.bin -m update
          git push
